dist: xenial
language: python
sudo: false

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libglu1-mesa xvfb

matrix:
  include:
    - name: "pip 3.7"
      python: 3.7

install:
  - pip -V
  - pip install -r requirements.txt;
  - pip install coverage coveralls nose
  - pip list
  - python --version

script:
  - xvfb-run -s "-screen 0 1400x900x24" nosetests --with-coverage --cover-package=gym_ultrasonic
  - coveralls
